
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaywtxmcyigetfsfiyaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhheXd0eG1jeWlnZXRmc2ZpeWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTAwODcsImV4cCI6MjA2MjkyNjA4N30.oaABqoH5KjMmRMUSGnX-JA1wrRX_Ud0E65wKJWQH4tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Support passwordless magic links
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
